#!/usr/bin/env python3

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/my_teams.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from src.interact import *
from src.teams_cli import do_request
from functools import partial

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.sub_process = None

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1285, 1000)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title_label = QtWidgets.QLabel(self.centralwidget)
        self.title_label.setGeometry(QtCore.QRect(460, 20, 311, 101))
        self.title_label.setObjectName("title_label")

        self.cmd_entry = QtWidgets.QLineEdit(self.centralwidget)
        self.cmd_entry.setGeometry(QtCore.QRect(190, 148, 921, 41))
        self.cmd_entry.setObjectName("cmd_entry")
        self.cmd_label = QtWidgets.QLabel(self.centralwidget)
        self.cmd_label.setGeometry(QtCore.QRect(130, 160, 80, 21))
        self.cmd_label.setObjectName("cmd_label")

        self.output_box = QtWidgets.QTextEdit(self.centralwidget)
        self.output_box.setGeometry(QtCore.QRect(40, 320, 1100, 250))
        self.output_box.setReadOnly(True)
        self.output_box.setObjectName("output_box")
        self.log_box = QtWidgets.QTextEdit(self.centralwidget)
        self.log_box.setGeometry(QtCore.QRect(40, 620, 1100, 250))
        self.log_box.setReadOnly(True)
        self.log_box.setObjectName("log_box")

        self.output_label = QtWidgets.QLabel(self.centralwidget)
        self.output_label.setGeometry(QtCore.QRect(590, 290, 80, 21))
        self.output_label.setObjectName("output_label")
        self.log_label = QtWidgets.QLabel(self.centralwidget)
        self.log_label.setGeometry(QtCore.QRect(590, 590, 80, 21))
        self.log_label.setObjectName("log_label")
        self.help_btn = QtWidgets.QPushButton(self.centralwidget)
        self.help_btn.setGeometry(QtCore.QRect(1140, 10, 106, 30))
        self.help_btn.setObjectName("help_btn")
        self.logout_btn = QtWidgets.QPushButton(self.centralwidget)
        self.logout_btn.setGeometry(QtCore.QRect(1140, 210, 106, 30))
        self.logout_btn.setObjectName("logout_btn")
        self.listUsers_btn = QtWidgets.QPushButton(self.centralwidget)
        self.listUsers_btn.setGeometry(QtCore.QRect(1140, 60, 106, 30))
        self.listUsers_btn.setObjectName("listUsers_btn")
        self.list_btn = QtWidgets.QPushButton(self.centralwidget)
        self.list_btn.setGeometry(QtCore.QRect(1140, 110, 106, 30))
        self.list_btn.setObjectName("list_btn")
        self.info_btn = QtWidgets.QPushButton(self.centralwidget)
        self.info_btn.setGeometry(QtCore.QRect(1140, 160, 106, 30))
        self.info_btn.setObjectName("info_btn")
        self.send_btn = QtWidgets.QPushButton(self.centralwidget)
        self.send_btn.setGeometry(QtCore.QRect(190, 190, 921, 41))
        self.send_btn.setObjectName("send_btn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1285, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)


        self.retranslateUi(MainWindow)
        self.setBtnActions()
        self.putCmdPrefix()
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:48pt;\">My Teams</span></p></body></html>"))
        self.cmd_label.setText(_translate("MainWindow", "CMD"))
        self.output_label.setText(_translate("MainWindow", "Output"))
        self.log_label.setText(_translate("MainWindow", "Log"))
        self.help_btn.setText(_translate("MainWindow", "Help"))
        self.logout_btn.setText(_translate("MainWindow", "Logout"))
        self.listUsers_btn.setText(_translate("MainWindow", "List users"))
        self.list_btn.setText(_translate("MainWindow", "List"))
        self.info_btn.setText(_translate("MainWindow", "Info"))
        self.send_btn.setText(_translate("MainWindow", "Send"))

    def setBtnActions(self):
        self.send_btn.clicked.connect(self.send_cmd)

        self.help_btn.released.connect(partial(self.doNameAction, self.help_btn.text()))
        self.info_btn.released.connect(partial(self.doNameAction, self.info_btn.text()))
        self.logout_btn.released.connect(partial(self.doNameAction, self.logout_btn.text()))
        self.list_btn.released.connect(partial(self.doNameAction, self.list_btn.text()))
        self.listUsers_btn.released.connect(partial(self.doNameAction, "users"))

    def setSubProcess(self, process):
        self.sub_process = process

    def putCmdPrefix(self):
        self.cmd_entry.clear()
        self.cmd_entry.setText("/")

    #btn functions
    def send_cmd(self):
        print("butoon clicked")
        request = str(self.cmd_entry.text())
        request += "\n"
        (out, err) = do_request(self.sub_process, request)
        self.output_box.clear()
        self.log_box.clear()
        self.output_box.setText(out)
        self.log_box.setText(err)
        self.putCmdPrefix()

    def doNameAction(self, name):
        request = "/" + str(name).lower() + "\n"
        print("name",name)
        (out, err) = do_request(self.sub_process, request)
        self.output_box.clear()
        self.log_box.clear()
        self.output_box.setText(out)
        self.log_box.setText(err)
        self.putCmdPrefix()


def lauch_gui(argv, teams_process) -> int:
    app = QtWidgets.QApplication(argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    ui.setSubProcess(teams_process)
    MainWindow.show()
    return app.exec_()


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()
#     ui = Ui_MainWindow()
#     ui.setupUi(MainWindow)
#     MainWindow.show()
#     sys.exit(app.exec_())
